---
- name: Install some cool tools
  gather_facts: no
  hosts: all
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Install procexp
      win_chocolatey:
        name: procexp
        state: present
      
    - name: Install git
      win_chocolatey:
        name: git
        state: present